---
name: POE-Component-IRC-Plugin-Thanks
version: 0.02
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: make witty responses to "thank you"s
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE::Component::IRC::Plugin: 0.09
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::Thanks:
    file: lib/POE/Component/IRC/Plugin/Thanks.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
